### ISSUE TITLE
使用 v2 样式首页出现滚动条

### ISSUE THREAD

**Issue by tnqzh123** [g-plane/multi-index-style#1]
如下图，皮肤站版本 v3.3， 插件版本 1.0.2，开启了使用 Bing 今日美图（就算不开也会这样），浏览器出现滚动条，且需要下拉才能看见底部版权信息。浏览器是 Chrome 60。站点地址 https://mcskin.littleservice.cn
![snipaste_20170809_112432](https://user-images.githubusercontent.com/16630630/29103956-5c6a0344-7cf5-11e7-9488-f3eda3343631.png)
![fireshot screen capture 007 - littleskin - mcskin_littleservice_cn](https://user-images.githubusercontent.com/16630630/29103991-7093650e-7cf5-11e7-8972-e215d5ebdd31.png)

**Comment by g-plane** [comment]
这个的确是 bug。会修复的。
________________________________
